defmodule Exhs.Repo.Migrations.OrganizationsCore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"
      add :status, :text, null: false, default: "active"
      add :joined_at, :utc_datetime_usec
      add :activated_at, :utc_datetime_usec
      add :deactivated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :forening_id, :uuid, null: false
    end

    create unique_index(:memberships, [:forening_id, :user_id],
             name: "memberships_unique_user_per_forening_index"
           )

    create table(:foreninger, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:memberships) do
      modify :forening_id,
             references(:foreninger,
               column: :id,
               name: "memberships_forening_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:foreninger) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :subdomain, :text, null: false
      add :branding, :map, default: %{}
      add :kontingent_amount_cents, :bigint
      add :kontingent_currency, :text, default: "DKK"
      add :kontingent_stripe_price_id, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:foreninger, [:slug], name: "foreninger_unique_slug_index")

    create unique_index(:foreninger, [:subdomain], name: "foreninger_unique_subdomain_index")
  end

  def down do
    drop_if_exists unique_index(:foreninger, [:subdomain],
                     name: "foreninger_unique_subdomain_index"
                   )

    drop_if_exists unique_index(:foreninger, [:slug], name: "foreninger_unique_slug_index")

    alter table(:foreninger) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :kontingent_stripe_price_id
      remove :kontingent_currency
      remove :kontingent_amount_cents
      remove :branding
      remove :subdomain
      remove :slug
      remove :name
    end

    drop constraint(:memberships, "memberships_forening_id_fkey")

    alter table(:memberships) do
      modify :forening_id, :uuid
    end

    drop table(:foreninger)

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop_if_exists unique_index(:memberships, [:forening_id, :user_id],
                     name: "memberships_unique_user_per_forening_index"
                   )

    drop table(:memberships)
  end
end
