defmodule Exhs.Repo.Migrations.AddForeningBrandingUrls do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:foreninger) do
      add :logo_url, :text
      add :banner_url, :text
    end
  end

  def down do
    alter table(:foreninger) do
      remove :banner_url
      remove :logo_url
    end
  end
end
