defmodule Exhs.Repo.Migrations.AddUserProfileFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
      add :phone, :text
      add :address_line_1, :text
      add :address_line_2, :text
      add :postal_code, :text
      add :city, :text
      add :avatar_url, :text
      add :is_superadmin, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :is_superadmin
      remove :avatar_url
      remove :city
      remove :postal_code
      remove :address_line_2
      remove :address_line_1
      remove :phone
      remove :last_name
      remove :first_name
    end
  end
end
