defmodule Exhs.Repo.Migrations.GroupsAndTagging do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:member_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "member_groups_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "member_groups_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :group_id, :uuid, null: false
    end

    create unique_index(:member_groups, [:forening_id, :membership_id, :group_id],
             name: "member_groups_unique_member_group_index"
           )

    create table(:groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:member_groups) do
      modify :group_id,
             references(:groups,
               column: :id,
               name: "member_groups_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:groups) do
      add :name, :text, null: false
      add :description, :text
      add :color, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "groups_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:groups, [:forening_id, :name],
             name: "groups_unique_name_per_forening_index"
           )
  end

  def down do
    drop constraint(:groups, "groups_forening_id_fkey")

    drop_if_exists unique_index(:groups, [:forening_id, :name],
                     name: "groups_unique_name_per_forening_index"
                   )

    alter table(:groups) do
      remove :forening_id
      remove :updated_at
      remove :inserted_at
      remove :color
      remove :description
      remove :name
    end

    drop constraint(:member_groups, "member_groups_group_id_fkey")

    alter table(:member_groups) do
      modify :group_id, :uuid
    end

    drop table(:groups)

    drop constraint(:member_groups, "member_groups_forening_id_fkey")

    drop constraint(:member_groups, "member_groups_membership_id_fkey")

    drop_if_exists unique_index(:member_groups, [:forening_id, :membership_id, :group_id],
                     name: "member_groups_unique_member_group_index"
                   )

    drop table(:member_groups)
  end
end
