defmodule Exhs.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audit_events) do
      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "audit_events_forening_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:audit_events, "audit_events_forening_id_fkey")

    alter table(:audit_events) do
      remove :forening_id
    end
  end
end
