defmodule Exhs.Repo.Migrations.Ticketing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:event_ticket_types) do
      add :sales_starts_at, :utc_datetime_usec
      add :sales_ends_at, :utc_datetime_usec
      add :allow_multiple, :boolean, null: false, default: false
    end

    create table(:event_ticket_type_questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text, null: false
      add :field_type, :text, null: false, default: "text"
      add :options, {:array, :text}, default: []
      add :required, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_ticket_type_questions_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ticket_type_id,
          references(:event_ticket_types,
            column: :id,
            name: "event_ticket_type_questions_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:event_ticket_type_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_ticket_type_groups_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ticket_type_id,
          references(:event_ticket_types,
            column: :id,
            name: "event_ticket_type_groups_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "event_ticket_type_groups_group_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:event_ticket_type_groups, [:forening_id, :ticket_type_id, :group_id],
             name: "event_ticket_type_groups_unique_ticket_type_group_index"
           )

    alter table(:event_registrations) do
      add :held_until, :utc_datetime_usec
    end

    drop_if_exists unique_index(
                     :event_registrations,
                     [:forening_id, :membership_id, :ticket_type_id],
                     name: "event_registrations_one_per_ticket_type_index"
                   )

    create unique_index(:event_registrations, [:forening_id, :membership_id, :ticket_type_id],
             name: "event_registrations_one_per_ticket_type_index",
             where: "(status != 'cancelled')"
           )

    create table(:event_orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "building"
      add :total_cents, :bigint, null: false, default: 0
      add :currency, :text, null: false, default: "DKK"
      add :held_until, :utc_datetime_usec
      add :stripe_checkout_session_id, :text
      add :paid_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_orders_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "event_orders_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "event_orders_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:event_order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :item_type, :text, null: false
      add :quantity, :bigint, null: false, default: 1
      add :unit_price_cents, :bigint, null: false, default: 0
      add :responses, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_order_items_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :order_id,
          references(:event_orders,
            column: :id,
            name: "event_order_items_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ticket_type_id,
          references(:event_ticket_types,
            column: :id,
            name: "event_order_items_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )

      add :add_on_id, :uuid
      add :registration_id, :uuid
    end

    create table(:event_add_ons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:event_order_items) do
      modify :add_on_id,
             references(:event_add_ons,
               column: :id,
               name: "event_order_items_add_on_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :registration_id,
             references(:event_registrations,
               column: :id,
               name: "event_order_items_registration_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:event_add_ons) do
      add :name, :text, null: false
      add :description, :text
      add :price_cents, :bigint, null: false, default: 0
      add :currency, :text, null: false, default: "DKK"
      add :capacity, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_add_ons_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "event_add_ons_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:event_add_ons, "event_add_ons_forening_id_fkey")

    drop constraint(:event_add_ons, "event_add_ons_event_id_fkey")

    alter table(:event_add_ons) do
      remove :event_id
      remove :forening_id
      remove :updated_at
      remove :inserted_at
      remove :capacity
      remove :currency
      remove :price_cents
      remove :description
      remove :name
    end

    drop constraint(:event_order_items, "event_order_items_add_on_id_fkey")

    drop constraint(:event_order_items, "event_order_items_registration_id_fkey")

    alter table(:event_order_items) do
      modify :registration_id, :uuid
      modify :add_on_id, :uuid
    end

    drop table(:event_add_ons)

    drop constraint(:event_order_items, "event_order_items_forening_id_fkey")

    drop constraint(:event_order_items, "event_order_items_order_id_fkey")

    drop constraint(:event_order_items, "event_order_items_ticket_type_id_fkey")

    drop table(:event_order_items)

    drop constraint(:event_orders, "event_orders_forening_id_fkey")

    drop constraint(:event_orders, "event_orders_membership_id_fkey")

    drop constraint(:event_orders, "event_orders_event_id_fkey")

    drop table(:event_orders)

    drop_if_exists unique_index(
                     :event_registrations,
                     [:forening_id, :membership_id, :ticket_type_id],
                     name: "event_registrations_one_per_ticket_type_index"
                   )

    create unique_index(:event_registrations, [:forening_id, :membership_id, :ticket_type_id],
             name: "event_registrations_one_per_ticket_type_index"
           )

    alter table(:event_registrations) do
      remove :held_until
    end

    drop constraint(:event_ticket_type_groups, "event_ticket_type_groups_forening_id_fkey")

    drop constraint(:event_ticket_type_groups, "event_ticket_type_groups_ticket_type_id_fkey")

    drop constraint(:event_ticket_type_groups, "event_ticket_type_groups_group_id_fkey")

    drop_if_exists unique_index(
                     :event_ticket_type_groups,
                     [:forening_id, :ticket_type_id, :group_id],
                     name: "event_ticket_type_groups_unique_ticket_type_group_index"
                   )

    drop table(:event_ticket_type_groups)

    drop constraint(:event_ticket_type_questions, "event_ticket_type_questions_forening_id_fkey")

    drop constraint(
           :event_ticket_type_questions,
           "event_ticket_type_questions_ticket_type_id_fkey"
         )

    drop table(:event_ticket_type_questions)

    alter table(:event_ticket_types) do
      remove :allow_multiple
      remove :sales_ends_at
      remove :sales_starts_at
    end
  end
end
