defmodule Exhs.Repo.Migrations.Localization do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :locale, :text, null: false, default: "da"
    end
  end

  def down do
    alter table(:users) do
      remove :locale
    end
  end
end
