defmodule Exhs.Repo.Migrations.BillingKontingent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:memberships) do
      add :stripe_customer_id, :text
    end

    alter table(:foreninger) do
      add :stripe_account_id, :text
      add :stripe_account_status, :text, null: false, default: "none"
    end

    create table(:billing_subscriptions_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :forening_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "billing_subscriptions_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:billing_subscriptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_subscription_id, :text, null: false
      add :stripe_customer_id, :text, null: false
      add :status, :text, null: false
      add :current_period_start, :utc_datetime_usec
      add :current_period_end, :utc_datetime_usec
      add :cancel_at_period_end, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "billing_subscriptions_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "billing_subscriptions_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:billing_subscriptions, [:forening_id, :membership_id],
             name: "billing_subscriptions_one_active_per_membership_index"
           )

    create unique_index(:billing_subscriptions, [:forening_id, :stripe_subscription_id],
             name: "billing_subscriptions_unique_stripe_subscription_id_index"
           )

    create table(:billing_payments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :forening_id, :uuid, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "billing_payments_versions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nothing,
            on_update: :update_all
          )
    end

    create table(:billing_payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :payable_type, :text, null: false
      add :payable_id, :uuid, null: false
      add :amount_cents, :bigint, null: false
      add :currency, :text, null: false, default: "DKK"
      add :status, :text, null: false
      add :stripe_payment_intent_id, :text
      add :stripe_charge_id, :text
      add :description, :text
      add :paid_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "billing_payments_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:billing_payments, [:forening_id, :stripe_payment_intent_id],
             name: "billing_payments_unique_stripe_payment_intent_id_index"
           )
  end

  def down do
    drop constraint(:billing_payments, "billing_payments_forening_id_fkey")

    drop_if_exists unique_index(:billing_payments, [:forening_id, :stripe_payment_intent_id],
                     name: "billing_payments_unique_stripe_payment_intent_id_index"
                   )

    drop table(:billing_payments)

    drop constraint(:billing_payments_versions, "billing_payments_versions_user_id_fkey")

    drop table(:billing_payments_versions)

    drop constraint(:billing_subscriptions, "billing_subscriptions_forening_id_fkey")

    drop constraint(:billing_subscriptions, "billing_subscriptions_membership_id_fkey")

    drop_if_exists unique_index(:billing_subscriptions, [:forening_id, :stripe_subscription_id],
                     name: "billing_subscriptions_unique_stripe_subscription_id_index"
                   )

    drop_if_exists unique_index(:billing_subscriptions, [:forening_id, :membership_id],
                     name: "billing_subscriptions_one_active_per_membership_index"
                   )

    drop table(:billing_subscriptions)

    drop constraint(
           :billing_subscriptions_versions,
           "billing_subscriptions_versions_user_id_fkey"
         )

    drop table(:billing_subscriptions_versions)

    alter table(:foreninger) do
      remove :stripe_account_status
      remove :stripe_account_id
    end

    alter table(:memberships) do
      remove :stripe_customer_id
    end
  end
end
