defmodule Exhs.Repo.Migrations.Events do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :location, :text
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec
      add :published, :boolean, null: false, default: false
      add :membership_required, :boolean, null: false, default: true
      add :cover_image_url, :text
      add :registration_opens_at, :utc_datetime_usec
      add :registration_closes_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "events_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:event_ticket_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :price_cents, :bigint, null: false, default: 0
      add :currency, :text, null: false, default: "DKK"
      add :capacity, :bigint
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_ticket_types_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :event_id,
          references(:events,
            column: :id,
            name: "event_ticket_types_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:event_ticket_types, [:forening_id, :name, :event_id],
             name: "event_ticket_types_unique_name_per_event_index"
           )

    create table(:event_registrations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :registered_at, :utc_datetime_usec
      add :cancelled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :forening_id,
          references(:foreninger,
            column: :id,
            name: "event_registrations_forening_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :ticket_type_id,
          references(:event_ticket_types,
            column: :id,
            name: "event_registrations_ticket_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :membership_id,
          references(:memberships,
            column: :id,
            name: "event_registrations_membership_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:event_registrations, [:forening_id, :membership_id, :ticket_type_id],
             name: "event_registrations_one_per_ticket_type_index"
           )
  end

  def down do
    drop constraint(:event_registrations, "event_registrations_forening_id_fkey")

    drop constraint(:event_registrations, "event_registrations_ticket_type_id_fkey")

    drop constraint(:event_registrations, "event_registrations_membership_id_fkey")

    drop_if_exists unique_index(
                     :event_registrations,
                     [:forening_id, :membership_id, :ticket_type_id],
                     name: "event_registrations_one_per_ticket_type_index"
                   )

    drop table(:event_registrations)

    drop constraint(:event_ticket_types, "event_ticket_types_forening_id_fkey")

    drop constraint(:event_ticket_types, "event_ticket_types_event_id_fkey")

    drop_if_exists unique_index(:event_ticket_types, [:forening_id, :name, :event_id],
                     name: "event_ticket_types_unique_name_per_event_index"
                   )

    drop table(:event_ticket_types)

    drop constraint(:events, "events_forening_id_fkey")

    drop table(:events)
  end
end
