defmodule Exhs.Repo.Migrations.AshEventsMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists table(:foreninger_versions)
    drop_if_exists table(:memberships_versions)
    drop_if_exists table(:groups_versions)
    drop_if_exists table(:member_groups_versions)
    drop_if_exists table(:billing_subscriptions_versions)
    drop_if_exists table(:billing_payments_versions)

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :record_id, :uuid, null: false
      add :version, :bigint, null: false, default: 1
      add :metadata, :map, null: false, default: %{}
      add :data, :map, null: false, default: %{}
      add :changed_attributes, :map, null: false, default: %{}
      add :occurred_at, :utc_datetime_usec, null: false
      add :resource, :text, null: false
      add :action, :text, null: false
      add :action_type, :text, null: false
      add :user_id, :uuid
    end
  end

  def down do
    drop table(:audit_events)
  end
end
